var mongoose = require('mongoose'),
    uniqueValidator = require('mongoose-unique-validator'),
    Schema = mongoose.Schema;

function upperCase(val) {
  return val.toString.toUpperCase();
}

var Cuestionario = new Schema({
    codigo: { type: String, index: true, unique: true, required: true },
    fecha_aplicacion: { type: String, set: upperCase, required: true, default: 'SIN INFORMACION' },
    municipio_encuesta: { type: String, set: upperCase, required: true, default: 'SIN INFORMACION' },
    nombre_organizacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    sigla_organizacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    direccion_organizacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    municipio: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    comuna: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    corregimiento: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    vereda: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    barrio: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    telefono_fijo: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    celular: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    correo_electronico: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    tipo_organizacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_cual_tipo_organizacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    objetivo_organizacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cobertura_organiza: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    motivo_constitucion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    fecha_constitucion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    perso_juridica: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    num_personeria: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    requisitos_asociados: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuales_requisitos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuantos_asociados_inicios: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuantos_asociados_actualmente: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    motivo_aumentdismi: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    figura_directiva: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    como_elige_directivos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    comite_grupo_mesas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    tipo_de_comites: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otros_cual_comite: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    frecuen_figudirectiva: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_frecuenc: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    frecuencia_reune_directivos_socios: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_frecuencia_reune_directivos_socios: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    mecanismo_decision: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_cual_mecanism: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    quien_decide: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_cual_quien_decide: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    conflictos_entre_integrantes: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otros_conflictos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    como_tramitan_conflictos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_como_tramitan_conflictos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    registra_diferencial: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_cual_diferencial: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    como_registra_diferencial: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_como_registra_diferencial: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    enfoque_grupos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_cual_enfoque: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    asociados_no_victimas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    hechos_victimizantes_asociados: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otros_cuales_hechos_victimizantes: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    hechos_victimizantes_mas_frecuentes_1: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    hechos_victimizantes_mas_frecuentes_2: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    hechos_victimizantes_mas_frecuentes_3: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    hechos_victimizantes_mas_frecuentes_4: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    trabajo_por_hvespecifico: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    tipos_victimiz_trabajo_por: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_tipos_victimiz_trabajo_por: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    org_cuenta_con: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    bienes: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    lugar_fisico: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    relacion_lugar: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    quien_financia: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    forma_financia: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_financia: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    recursos_propios_como: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otros_recursos_propios: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    tiene_recursos_funcionamiento: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuanto_dinero_2013: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuanto_dinero_mas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    dineros_proyectos_2013: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuanto_dinero_admin_2013: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuanto_dinero_mas_proyecto_2013: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    funcion_interno: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    planeacion_ejecucion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_destino_recursos_planeacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    cuales_medios_comunicacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_medios_comunicacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    rendicion_cuentas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    forma_rendicion_cuentas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_forma_rendicion_cuentas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    frecuencia_rendicion_cuentas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_frecuencia_rendicion_cuentas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    medios_utiliza_comunicacion_interna: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otros_medios_comunicacion_interna: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    medios_difusion_externos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_medios_difusion_externos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    mecanismos_recepcion_informacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otros_mecanismos_recepcion_informacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    han_recibido_formacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_formacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    se_socializa_conocimiento: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    replica_formacion_a_organizaciones_victimas_cercanas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    derechos_organizacion_trabaja: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otros_derechos_organizacion_trabaja: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_orienta_asociados: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_si_orienta_asociados: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_estrategias_derechos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_organizacion_estrategias_derechos: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_circula_informacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_si_circula_informacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otro_organizacion_si_circula_informacion: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_orienta_ante_estado: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_si_orienta_ante_estado: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_orienta_fiscalia: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_orienta_ley1448: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_orienta_despojo: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_inscrita_otras_orga: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_si_inscrita_otras_orga: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_participa_otras_orga: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_organizacion_participa_otras_orga: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_motivacion_otras_orga: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_organizacion_motivacion_otras_orga: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_asiste_otros_espacios_participa: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_si_asiste_otros_espacios_participa: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_comite_mmpv: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_grupo_tematico_mmpv: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_si_cual_grupo_tematico_mmpv: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_delegada_ctjt: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_subcomite_ctjt: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_subcomite_ctjt_cuales: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_participa_en: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_organizacion_participa_en: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_dificultades_efectiva_participa: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    otra_organizacion_dificultades_efectiva_participa: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_logra_proyectos_con_munadmon: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_cuales_propuestas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_seguimiento_a_propuestas: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_quienes_apoyan: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    nombre_organizacion_quienes_apoyan: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_apoyo_en: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    organizacion_apoyo_en: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    nombre_facilitador: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    institucion_representa_facilitador: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    telefono_facilitador: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    correo_electronico_facilitador: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    firma_facilitador: { type: String, set: upperCase, default: 'SIN INFORMACION' },
    observaciones: { type: String, set: upperCase, default: 'SIN INFORMACION' }
});

Cuestionario.plugin(uniqueValidator);

module.exports = mongoose.model('Cuestionario', Cuestionario);
